<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Wowslider.com generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Wowslider.com" />
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>

	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7;margin:auto">
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/d1.jpg" alt="" title="" id="wows1_0"/>Ven y descubre la magia del Todo Incluido Decameron, un concepto para pasar las mejores vacaciones</li>
<li><img src="data1/images/d2.jpg" alt="" title="" id="wows1_1"/>En nuestros Hoteles podrás disfrutar exquisitos y variados desayunos y almuerzos al estilo buffet</li>
<li><img src="data1/images/d3.jpg" alt="" title="" id="wows1_2"/>Acompaña tus vacaciones con las bebidas que tú desees, con nosotros puedes disfrutar bares abiertos en playas y piscinas en donde podrás encontrar cocteles con y sin alcohol, jugos de frutas, gaseosas y más</li>
<li><img src="data1/images/d4.jpg" alt="" title="" id="wows1_3"/>En Decameron encuentras diversión para todos, te ofrecemos una amplia variedad de actividades, para todas las edades y gustos</li>
<li><img src="data1/images/d7.jpg" alt="" title="" id="wows1_4"/>Cada una de nuestras habitaciones está equipada con todas las comodidades necesarias para que vivas una placentera estadía, en donde tendrás una experiencia única de relajación, descanso y comodidad ¡Es hora de darte el descanso que te mereces!.</li>
<li><img src="data1/images/d9.jpg" alt="" title="" id="wows1_5"/>Ven y descubre la magia del Todo Incluido Decameron, un concepto para pasar las mejores vacaciones</li>
<li><a href="http://wowslider.com/vf"><img src="data1/images/d14.jpg" alt="full screen slider" title="" id="wows1_6"/></a>Ven y realiza tus reuniones en nuestras modernas instalaciones, equipadas con todo lo necesario para tus eventos empresariales</li>
<li><img src="data1/images/d15.jpg" alt="" title="" id="wows1_7"/>En nuestros Hoteles puedes disfrutar de las más hermosas playas y piscinas para adultos y niños que inspiran descanso y relajación, donde podrás disfrutar en plenitud de hermosos paisajes e imágenes que jamás olvidarás.</li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title=""><img src="data1/tooltips/d1.jpg" alt=""/>1</a>
<a href="#" title=""><img src="data1/tooltips/d2.jpg" alt=""/>2</a>
<a href="#" title=""><img src="data1/tooltips/d3.jpg" alt=""/>3</a>
<a href="#" title=""><img src="data1/tooltips/d4.jpg" alt=""/>4</a>
<a href="#" title=""><img src="data1/tooltips/d7.jpg" alt=""/>5</a>
<a href="#" title=""><img src="data1/tooltips/d9.jpg" alt=""/>6</a>
<a href="#" title=""><img src="data1/tooltips/d14.jpg" alt=""/>7</a>
<a href="#" title=""><img src="data1/tooltips/d15.jpg" alt=""/>8</a>
</div></div><span class="wsl"><a href="http://wowslider.com">wowslider.com</a> by WOWSlider.com v6.4</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>